package model.voluntary

data class RequestVoluntary (
                     val name: String,
                     val surname: String,
                     val genre: String,
                     val transport: String,
                     val foodRestriction: Int,
                     val merchandising: Int,
                     val moreInfo: String,
                     val children: Boolean,
                     val comeChildren: Boolean,
                     val nChildren: Int,
                     val ageChildren: Int,
                     val hotel: Int,
                     val priceTicket: Float,
                     val numberVisit: Int,
                     val image: String,
                     val company: String,
                     val rating: Int,
                     val dateRequestTicket: String,
                     val dateGrantTicket: String,
                     val datePayedTicket: String,
                     val timesExpiredTicket: Int,
                     val timesAbsent: Int,
                     val gdg: String,
                     val idHotel: Int,
                     val cost: Float,
                     val email: String)