package model.attendee

data class RequestAttendee(
    val name: String,
    val surname: String,
    val foodRestriction: String,
    val genre: String,
    val transport: String,
    val merchandising: Int,
    val moreInfo: String,
    val children: Boolean,
    val comeChildren: Boolean,
    val nChildren: Int,
    val ageChildren: Int,
    val hotel: Int,
    val priceTicket: Float,
    val numberVisit: Int,
    val image: String,
    val company: String,
    val rating: Int,
    val dateRequestTicket: String,
    val dateGrantTicket: String,
    val datePayedTicket: String,
    val timesExpiredTicket: Int,
    val timesAbsent: Int,
    val email: String)